language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
script:
- npm run build
- npm run test:ci
- npm install codecov -g
after_success:
- codecov -f coverage/*.json
deploy:
  skip_cleanup: true
  provider: npm
  email: umstek@live.com
  on:
    tags: true
    repo: umstek/sampler
    branch: master
  api_key:
    secure: Y/S4Kk9uWXwTDyfzH3P5bL+pT7AUtB04NXhb3G0WZsKvsyLbyoWsfBqTxI6qpKC9t3DnWlTRvObnZOO2xq11qGJyQrpic/fwQoTpwdNmRP2+pQXA8RQZnBDg5BKzjhRih0c9I/1/ytmpQ40u5jZYm7Rc7eHWiM7LinSt0at1bFbcCKBWGlnX2pDjFeQdeHVnk2nJIK0+EaBXe2cKYE9ILiALyKs7FgcFEOlf/TBE/TWdxe5omDBy4CL0hlJHTiAX6yiFp467+mJUPhQF67E+yy4lOwfJMwRJZ3IMtF0606hws3bBDTnx52CHE02lE34Z41EguhbopiA8YIfyDFEb0q36DlZxjO4M+mpOlrtHjnxmUR2K1Se1ATN9syctuMWmUrAIJ7vdSQOHYaGArYx1wiy9Wa3n7dXYUvz0huibq9T9iSbrmjvjaTxXrKE5ywBepjl5l5HHlZ1bW8/o5QnFALnXzUQDbgvifT8IBQEWC3UDtc/gkOzy0YB6o0J94RIqd/1oCyPJAcKb5m0OtObLd1ehQ7ji2eNqfwymeCQjGi8GlFfGSlDo+W3aV95LLjTm6SQziCKjm5AeIfNqD66/IG1iG1WXzGwvfw0WfSovvPchiCQBCGLytGzO40tUow0oCRGoD/1PqsaMI7ehap/IKW3YvbszdtbMLGlRqNCm+D4=
