language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
script:
- npm run build
- npm run test:ci
- npm install codecov -g
after_success:
- codecov -f coverage/*.json
deploy:
  skip_cleanup: true
  provider: npm
  email: umstek@live.com
  on:
    tags: true
    repo: umstek/sampler
    branch: master
  api_key:
    secure: $NPM_TOKEN
