name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v4
        with:
          node-version: 12
      - run: npm install
      - run: npm build
      - run: npm run test:ci
      - name: codecov
        uses: codecov/codecov-action@v1.0.5
        with:
          token: ${{secrets.codecov}}
          fail_ci_if_error: true
          file: ./coverage/coverage-final.json
